-- MySQL Script generated by MySQL Workbench
-- Sat Jun 12 09:00:20 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema taskforce
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema taskforce
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `taskforce` DEFAULT CHARACTER SET utf8 ;
USE `taskforce` ;

-- -----------------------------------------------------
-- Table `taskforce`.`cities`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `taskforce`.`cities` (
  `ID` INT NOT NULL,
  `city_name` VARCHAR(45) NOT NULL,
  `coord` POINT NOT NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `taskforce`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `taskforce`.`user` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(256) NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `cityID` INT NULL,
  `password_hash` VARCHAR(32) NOT NULL,
  `birthday` DATE NULL,
  `phone` INT NULL,
  `skype` VARCHAR(45) NULL,
  `avatar_ID` INT NULL COMMENT 'Contains path to jpg\\png',
  `option_notification_new_message` TINYINT(1) NULL,
  `option_notification_task_change` TINYINT(1) NULL,
  `option_notification_new_comment` TINYINT(1) NULL,
  `option_privacy_do_not_show_profile` TINYINT(1) NULL,
  `option_privacy_showContactsOnlyToExecutor` TINYINT(1) NULL,
  `photos_of_work_ID` INT NULL,
  `is_executor` TINYINT(1) NULL,
  `date_of_registration` DATETIME NOT NULL,
  `rating` FLOAT NULL,
  `another_contact` VARCHAR(45) NULL,
  `information_about_user` VARCHAR(45) NULL,
  PRIMARY KEY (`ID`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE,
  UNIQUE INDEX `phone_UNIQUE` (`phone` ASC) VISIBLE,
  UNIQUE INDEX `ID_UNIQUE` (`ID` ASC) VISIBLE,
  INDEX `ID_idx` (`cityID` ASC) VISIBLE,
  UNIQUE INDEX `skype_UNIQUE` (`skype` ASC) VISIBLE,
  CONSTRAINT `ID`
    FOREIGN KEY (`cityID`)
    REFERENCES `taskforce`.`cities` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `taskforce`.`categories`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `taskforce`.`categories` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `category_name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `taskforce`.`status`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `taskforce`.`status` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `taskforce`.`task`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `taskforce`.`task` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `status` INT NOT NULL,
  `creator_ID` INT NOT NULL,
  `category_ID` INT NOT NULL,
  `task_price` INT NOT NULL,
  `attachment_ID` INT NULL,
  `name` VARCHAR(45) NOT NULL,
  `description` VARCHAR(500) NOT NULL,
  `done` TINYINT(1) NOT NULL DEFAULT 0,
  `address` VARCHAR(100) NOT NULL,
  `deadline` DATETIME NULL,
  `date_of_creation` DATETIME NULL,
  `executor_ID` INT NULL,
  PRIMARY KEY (`ID`),
  INDEX `ID_idx1` (`category_ID` ASC) VISIBLE,
  INDEX `ID_idx2` (`creator_ID` ASC) VISIBLE,
  INDEX `ID_idx3` (`status` ASC) VISIBLE,
  CONSTRAINT `ID`
    FOREIGN KEY (`category_ID`)
    REFERENCES `taskforce`.`categories` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `ID`
    FOREIGN KEY (`creator_ID`)
    REFERENCES `taskforce`.`user` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `ID`
    FOREIGN KEY (`status`)
    REFERENCES `taskforce`.`status` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `taskforce`.`response`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `taskforce`.`response` (
  `task_ID` INT NOT NULL,
  `responser_ID` INT NOT NULL,
  `response_price` INT NOT NULL,
  `comment` VARCHAR(45) NULL,
  INDEX `ID_idx` (`task_ID` ASC) VISIBLE,
  INDEX `ID_idx1` (`responser_ID` ASC) VISIBLE,
  CONSTRAINT `ID`
    FOREIGN KEY (`task_ID`)
    REFERENCES `taskforce`.`task` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `ID`
    FOREIGN KEY (`responser_ID`)
    REFERENCES `taskforce`.`user` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `taskforce`.`attachments`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `taskforce`.`attachments` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `path` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `taskforce`.`chats`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `taskforce`.`chats` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `recepient_ID` INT NOT NULL,
  `sender_ID` INT NOT NULL,
  `message` VARCHAR(100) NOT NULL,
  `viewed` TINYINT(1) NOT NULL DEFAULT 0,
  `time` DATETIME NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `taskforce`.`reviews`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `taskforce`.`reviews` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `user_ID` INT NOT NULL,
  `reviewer_ID` INT NOT NULL,
  `mark` INT NOT NULL,
  `text` VARCHAR(150) NULL,
  PRIMARY KEY (`ID`),
  INDEX `ID_idx` (`user_ID` ASC) VISIBLE,
  INDEX `ID_idx1` (`reviewer_ID` ASC) VISIBLE,
  CONSTRAINT `ID`
    FOREIGN KEY (`user_ID`)
    REFERENCES `taskforce`.`user` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `ID`
    FOREIGN KEY (`reviewer_ID`)
    REFERENCES `taskforce`.`user` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `taskforce`.`attachment`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `taskforce`.`attachment` (
  `user_ID` INT NULL,
  `attachments_ID` INT NULL,
  INDEX `ID_idx` (`user_ID` ASC) VISIBLE,
  INDEX `ID_idx1` (`attachments_ID` ASC) VISIBLE,
  CONSTRAINT `ID`
    FOREIGN KEY (`user_ID`)
    REFERENCES `taskforce`.`user` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `ID`
    FOREIGN KEY (`attachments_ID`)
    REFERENCES `taskforce`.`attachments` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `taskforce`.`attachment_task`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `taskforce`.`attachment_task` (
  `task_ID` INT NULL,
  `attachments_ID` INT NULL,
  INDEX `ID_idx1` (`attachments_ID` ASC) VISIBLE,
  INDEX `ID_idx` (`task_ID` ASC) VISIBLE,
  CONSTRAINT `ID`
    FOREIGN KEY (`attachments_ID`)
    REFERENCES `taskforce`.`attachments` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `ID`
    FOREIGN KEY (`task_ID`)
    REFERENCES `taskforce`.`task` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
